services:
  nowen-note:
    image: {{DOCKERHUB_REPO}}:{{IMAGE_TAG}}
    container_name: nowen-note
    restart: unless-stopped
    ports:
      - "3501:3001"
    volumes:
      - "/var/apps/nowen-note/shares/nowen-note/data:/app/data"
    environment:
      - NODE_ENV=production
      - DB_PATH=/app/data/nowen-note.db
      - PORT=3001
